server.port=${REST_PORT:8001}
node.id=${NODE_ID:1}
node.grpc.port=${GRPC_PORT:50051}
node.peers=localhost:50051,localhost:50052,localhost:50053
spring.main.allow-bean-definition-overriding=true
logging.level.com.distributed=INFO
